/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:38011c28-d6a2-4972-a7fd-1739e6afd96a",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_3hTwSeufo",
    "aws_user_pools_web_client_id": "27anvq36hd6sk776eahv93r05i",
    "oauth": {
        "domain": "socially3fe368ff-3fe368ff-dev.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://main.d2mpmmgvvwzzqh.amplifyapp.com/",
        "redirectSignOut": "http://localhost:3000/,https://main.d2mpmmgvvwzzqh.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://hxjiruqidzhlxktoazyf7bqaqu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-76upse6fjvdxvezxb7gzpdkk3y",
    "aws_user_files_s3_bucket": "sociallyaec04659306c41c78d18becd1508e35b123626-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
